description: >
  This command build the AWS Lambda Go function executable
parameters:
  build-input-file:
    type: string
    default: main.go
  build-output-file:
    type: string
    default: main
  package-output-file:
    type: string
    default: pulumi/lambda.zip
steps:
  - run:
      name: Build executable
      environment:
        INPUT_FILE: << parameters.build-input-file >>
        OUTPUT_FILE: << parameters.build-output-file >>
      command: << include(scripts/build.sh) >>
  - run:
      name: Package executable
      environment:
        INPUT_FILE: << parameters.build-output-file >>
        OUTPUT_FILE: << parameters.package-output-file >>
      command: << include(scripts/package.sh) >>
  - persist_to_workspace:
      name: Store package
      root: .
      paths:
        - << parameters.package-output-file >>
