description: >
  This command build the AWS Lambda Go function executable

parameters:
  build-input-file:
    type: string
    default: main.go
  build-output-file:
    type: string
    default: main
  build-architecture:
    type: string
    default: amd64
  package-output-file:
    type: string
    default: deploy/lambda.zip

steps:
  - run:
      name: Build executable
      resource_class: arm.medium
      environment:
        INPUT_FILE: << parameters.build-input-file >>
        OUTPUT_FILE: << parameters.build-output-file >>
        ARCHITECTURE: << parameters.build-architecture >>
      command: << include(scripts/build.sh) >>
  - run:
      name: Package executable
      environment:
        INPUT_FILE: << parameters.build-output-file >>
        OUTPUT_FILE: << parameters.package-output-file >>
      command: << include(scripts/package.sh) >>
  - persist_to_workspace:
      name: Store package
      root: .
      paths:
        - << parameters.package-output-file >>
