description: >
  This job build the AWS Lambda Go function executable

executor: golang

parameters:
  build-input-file:
    type: string
    default: main.go
  build-output-file:
    type: string
    default: main
  build-architecture:
    type: string
    default: amd64
  package-output-file:
    type: string
    default: deploy/lambda.zip

steps:
  - run: go version
  - run: pulumi version
  - checkout
  - build:
      build-input-file: << parameters.build-input-file >>
      build-output-file: << parameters.build-output-file >>
      build-architecture: << parameters.build-architecture >>
      package-output-file: << parameters.package-output-file >>
