description: >
  Default executor using Docker and Go.
docker:
  - image: "cimg/go:<<parameters.tag>>"
parameters:
  tag:
    default: "1.16"
    description: >
      Pick a specific circleci/go image variant:
      https://hub.docker.com/r/cimg/go/tags
    type: string
